package interfaz; // Nicolas Rodriguez y Manuel Ackerman
import dominio.Sistema;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utilidades.Utilidades;

public class VentanaRegistrarDueño extends javax.swing.JFrame {

    private Utilidades util;
    
    public VentanaRegistrarDueño(Sistema modelo) {
        this.modelo = modelo;
        this.util = new Utilidades();
        initComponents();
        ImageIcon icon = new ImageIcon("icono.png");
        this.setIconImage(icon.getImage());
        setLocationRelativeTo(null); //Centra ventana
        lblReingresoNombre.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistrarDueño = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblExperiencia = new javax.swing.JLabel();
        btnCrearDueño = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        fieldNombre = new javax.swing.JTextField();
        spinnerEdad = new javax.swing.JSpinner();
        spinnerExperiencia = new javax.swing.JSpinner();
        lblAños = new javax.swing.JLabel();
        lblRegistrarDueño = new javax.swing.JLabel();
        lblReingresoNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar dueño - Mercado");
        setResizable(false);
        getContentPane().setLayout(null);

        lblNombre.setText("Nombre:");

        lblEdad.setText("Edad:");

        lblExperiencia.setText("Experiencia");

        btnCrearDueño.setText("Crear dueño");
        btnCrearDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDueñoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });

        spinnerEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spinnerExperiencia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblAños.setText("(años)");

        lblRegistrarDueño.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegistrarDueño.setText("Registrar dueño");

        lblReingresoNombre.setForeground(new java.awt.Color(255, 0, 0));
        lblReingresoNombre.setText("* Reingrese el nombre");

        javax.swing.GroupLayout jPanelRegistrarDueñoLayout = new javax.swing.GroupLayout(jPanelRegistrarDueño);
        jPanelRegistrarDueño.setLayout(jPanelRegistrarDueñoLayout);
        jPanelRegistrarDueñoLayout.setHorizontalGroup(
            jPanelRegistrarDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarDueñoLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblRegistrarDueño))
            .addGroup(jPanelRegistrarDueñoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelRegistrarDueñoLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lblReingresoNombre))
            .addGroup(jPanelRegistrarDueñoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(spinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelRegistrarDueñoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(spinnerExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblAños, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelRegistrarDueñoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnCrearDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelRegistrarDueñoLayout.setVerticalGroup(
            jPanelRegistrarDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarDueñoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRegistrarDueño)
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistrarDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistrarDueñoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblNombre))
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblReingresoNombre)
                .addGap(3, 3, 3)
                .addGroup(jPanelRegistrarDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistrarDueñoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblEdad))
                    .addComponent(spinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelRegistrarDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRegistrarDueñoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelRegistrarDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExperiencia)
                            .addComponent(lblAños))))
                .addGap(26, 26, 26)
                .addGroup(jPanelRegistrarDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnCrearDueño)))
        );

        getContentPane().add(jPanelRegistrarDueño);
        jPanelRegistrarDueño.setBounds(0, 0, 400, 290);

        setBounds(0, 0, 414, 336);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDueñoActionPerformed
        fieldNombre.setBorder(BorderFactory.createLineBorder(util.COLOR_NEGRO));
        lblReingresoNombre.setVisible(false);
        String nombre = fieldNombre.getText();
        int edad = (int) (spinnerEdad.getValue());
        int exp = (int) (spinnerExperiencia.getValue());
        if(util.validarTxt(nombre)){
            String mensaje = "";
            if (modelo.dueñoUnico(nombre)) { // Si dueño es único
                modelo.agregarDueño(nombre, edad, exp);
                this.reset();
                mensaje = "Dueño '" + nombre + "' creado correctamente.";
            } else { // Si nombre de dueño ya existe
                mensaje = "Ya existe un dueño con el nombre '" + nombre + "' creado.\nEl nombre del dueño debe ser único.";
                fieldNombre.setBorder(BorderFactory.createLineBorder(util.COLOR_ROJO));
                lblReingresoNombre.setVisible(true); //Muestra label de reeingreso
            }
            JOptionPane.showMessageDialog(this, mensaje, "Informacion del sistema.", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "El nombre del dueño no puede ser vacío. Ingreselo.",
                    "Informacion del sistema.", JOptionPane.ERROR_MESSAGE);
            fieldNombre.setBorder(BorderFactory.createLineBorder(util.COLOR_ROJO));
            lblReingresoNombre.setVisible(true); //Muestra label de reeingreso
        }
        this.btnCrearDueño.setSelected(false);
    }//GEN-LAST:event_btnCrearDueñoActionPerformed

    public void reset() {
        fieldNombre.setText("");
        spinnerEdad.setValue(0);
        spinnerExperiencia.setValue(0);
    }
        
    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnCrearDueño;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JPanel jPanelRegistrarDueño;
    private javax.swing.JLabel lblAños;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblExperiencia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistrarDueño;
    private javax.swing.JLabel lblReingresoNombre;
    private javax.swing.JSpinner spinnerEdad;
    private javax.swing.JSpinner spinnerExperiencia;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;

} // Nicolas Rodriguez y Manuel Ackerman
