package interfaz; // Nicolas Rodriguez y Manuel Ackerman

import dominio.Mayorista;
import dominio.Producto;
import dominio.Puesto;
import dominio.Sistema;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utilidades.Utilidades;

public class VentanaRegistrarCompra extends javax.swing.JFrame implements PropertyChangeListener {

    private final static String TIPO_MOVIMIENTO = "Compra";

    public VentanaRegistrarCompra(Sistema modelo) {
        this.modelo = modelo;
        modelo.addPropertyChangeListener(this);
        initComponents();
        ImageIcon icon = new ImageIcon("icono.png");
        this.setIconImage(icon.getImage());
        setLocationRelativeTo(null); //Centra ventana
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistroCompra = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMayorista = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPuesto = new javax.swing.JList();
        lblSelPuesto = new javax.swing.JLabel();
        lblSelMayorista = new javax.swing.JLabel();
        lblSelProducto = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        spinnerPrecio = new javax.swing.JSpinner();
        spinnerCantidad = new javax.swing.JSpinner();
        btnComprar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaProducto = new javax.swing.JList();
        lblTipoVenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar compra- Mercado");
        setResizable(false);

        listaMayorista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaMayorista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaMayoristaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaMayorista);

        listaPuesto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaPuesto.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPuestoValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaPuesto);

        lblSelPuesto.setText("Seleccionar puesto:");

        lblSelMayorista.setText("Seleccionar mayorista:");

        lblSelProducto.setText("Seleccionar producto:");

        lblPrecio.setText("Precio:");

        lblCantidad.setText("Cantidad:");

        spinnerPrecio.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        spinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnComprar.setText("Registrar compra");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        listaProducto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaProducto.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaProductoValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaProducto);

        lblTipoVenta.setText("Tipo venta:");

        javax.swing.GroupLayout jPanelRegistroCompraLayout = new javax.swing.GroupLayout(jPanelRegistroCompra);
        jPanelRegistroCompra.setLayout(jPanelRegistroCompraLayout);
        jPanelRegistroCompraLayout.setHorizontalGroup(
            jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroCompraLayout.createSequentialGroup()
                .addGroup(jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroCompraLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblSelPuesto)
                        .addGap(267, 267, 267)
                        .addComponent(lblSelMayorista))
                    .addGroup(jPanelRegistroCompraLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegistroCompraLayout.createSequentialGroup()
                            .addGap(204, 204, 204)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnComprar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegistroCompraLayout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(lblSelProducto)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelRegistroCompraLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrecio)
                            .addComponent(lblCantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroCompraLayout.createSequentialGroup()
                                .addComponent(spinnerPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jPanelRegistroCompraLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        jPanelRegistroCompraLayout.setVerticalGroup(
            jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroCompraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelMayorista, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSelPuesto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelProducto)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spinnerPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCantidad)))
                .addGap(22, 22, 22)
                .addGroup(jPanelRegistroCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnComprar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanelRegistroCompraLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRegistroCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRegistroCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 750, 621);
    }// </editor-fold>//GEN-END:initComponents

    private void listaPuestoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPuestoValueChanged

    }//GEN-LAST:event_listaPuestoValueChanged

    private void listaMayoristaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaMayoristaValueChanged
        Mayorista mayorista = (Mayorista) listaMayorista.getSelectedValue();
        if (mayorista != null) {
            listaProducto.setListData(mayorista.getListaProductos().toArray());
        }else{
         
        }
    }//GEN-LAST:event_listaMayoristaValueChanged

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        Puesto puesto = (Puesto) listaPuesto.getSelectedValue();
        try {
            if (listaPuesto.getSelectedValue() != null && listaProducto.getSelectedValue() != null) {
                puesto.comprarProducto((Producto) listaProducto.getSelectedValue(), (int) spinnerCantidad.getValue());
                modelo.agregarMovimiento((int) spinnerCantidad.getValue(), (int) spinnerPrecio.getValue(), puesto, (Producto) listaProducto.getSelectedValue(), TIPO_MOVIMIENTO);
                JOptionPane.showMessageDialog(this, "¡La compra se realizo con exito!",
                        "Informacion del sistema.", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No fue posible realizar la compra del producto.\nRevise que todos los campos esten completos o sean correctos.",
                        "Informacion del sistema.", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hubo un error al realizar la compra.\nContacte con sistemas.",
                    "Informacion del sistema.", JOptionPane.INFORMATION_MESSAGE);
        }
        this.btnComprar.setSelected(false);
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void listaProductoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaProductoValueChanged
        if (listaProducto.getSelectedValue() != null) {
            Producto prod = (Producto) listaProducto.getSelectedValue();
            lblTipoVenta.setText("Tipo venta: " + Utilidades.devolverTipoVentaAMostrar(prod.getFormaVenta(), 1)); // Se setea en 1 para mostrar la forma de venta en singular
        } else {
            lblTipoVenta.setText("Tipo venta: ");
        }
    }//GEN-LAST:event_listaProductoValueChanged

    private void cargar() {
        listaPuesto.setListData(modelo.getListaPuestos().toArray());
        listaMayorista.setListData(modelo.getListaMayoristas().toArray());
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        cargar();
        if (listaMayorista.getSelectedValue() != null) {
            Mayorista m1 = (Mayorista) listaMayorista.getSelectedValue();
            listaProducto.setListData(m1.getListaProductos().toArray());
        }else{
            DefaultListModel listaModelo = new DefaultListModel();
            listaProducto.setModel(listaModelo);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JPanel jPanelRegistroCompra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSelMayorista;
    private javax.swing.JLabel lblSelProducto;
    private javax.swing.JLabel lblSelPuesto;
    private javax.swing.JLabel lblTipoVenta;
    private javax.swing.JList listaMayorista;
    private javax.swing.JList listaProducto;
    private javax.swing.JList listaPuesto;
    private javax.swing.JSpinner spinnerCantidad;
    private javax.swing.JSpinner spinnerPrecio;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
} // Nicolas Rodriguez y Manuel Ackerman

