package interfaz; // Nicolas Rodriguez y Manuel Ackerman

import dominio.Dueño;
import dominio.Sistema;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

public class VentanaConsultaDueño extends javax.swing.JFrame implements PropertyChangeListener {

    public VentanaConsultaDueño(Sistema modelo) {
        this.modelo = modelo;
        this.modelo.addPropertyChangeListener(this);
        initComponents();
        //Pone icono a la ventana
        ImageIcon icon = new ImageIcon("icono.png");
        this.setIconImage(icon.getImage());
        setLocationRelativeTo(null); //Centra ventana
        tablaDueños.setDefaultEditor(Object.class, null);
        tablaDueños.getTableHeader().setReorderingAllowed(false);
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVentanaConsultaDueño = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDueños = new javax.swing.JTable();
        lblDueños = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta dueño - Mercado");

        jScrollPane1.setViewportView(tablaDueños);

        lblDueños.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDueños.setText("Dueños ordenados alfabéticamente");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVentanaConsultaDueñoLayout = new javax.swing.GroupLayout(jPanelVentanaConsultaDueño);
        jPanelVentanaConsultaDueño.setLayout(jPanelVentanaConsultaDueñoLayout);
        jPanelVentanaConsultaDueñoLayout.setHorizontalGroup(
            jPanelVentanaConsultaDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentanaConsultaDueñoLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanelVentanaConsultaDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentanaConsultaDueñoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentanaConsultaDueñoLayout.createSequentialGroup()
                        .addComponent(lblDueños)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentanaConsultaDueñoLayout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(39, 39, 39))))
        );
        jPanelVentanaConsultaDueñoLayout.setVerticalGroup(
            jPanelVentanaConsultaDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentanaConsultaDueñoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblDueños)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentanaConsultaDueño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentanaConsultaDueño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 586, 437);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
     dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    
    public void cargar(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nombre");
        model.addColumn("Edad");
        model.addColumn("Experiencia");
        modelo.getListaDueños().sort(null);
        for (Dueño dueño : modelo.getListaDueños()){
            Object [] fila = {dueño.getNombre(), dueño.getEdad(), dueño.getAñosExp()};
            model.addRow(fila);
        }
        tablaDueños.setModel(model);
    }
    
        @Override
    public void propertyChange(PropertyChangeEvent evt) {
        cargar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanelVentanaConsultaDueño;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDueños;
    private javax.swing.JTable tablaDueños;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
} // Nicolas Rodriguez y Manuel Ackerman
