package interfaz; // Nicolas Rodriguez y Manuel Ackerman

import dominio.Producto;
import dominio.Puesto;
import dominio.Sistema;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import utilidades.*;

public class VentanaRegistrarVentaProducto extends javax.swing.JFrame {

    private final static String TIPO_MOVIMIENTO = "Venta";

    public VentanaRegistrarVentaProducto(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
        ImageIcon icon = new ImageIcon("icono.png");
        this.setIconImage(icon.getImage());
        setLocationRelativeTo(null); //Centra ventana
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneRegistarVentaProducto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPuestos = new javax.swing.JList();
        lblPuesto = new javax.swing.JLabel();
        lblSelProducto = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panelProductos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar venta de producto - Mercado");
        setResizable(false);
        getContentPane().setLayout(null);

        lstPuestos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPuestos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPuestosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPuestos);

        lblPuesto.setText("Seleccionar puesto:");

        lblSelProducto.setText("Seleccionar producto:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        panelProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelProductos.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(panelProductos);

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout jPaneRegistarVentaProductoLayout = new javax.swing.GroupLayout(jPaneRegistarVentaProducto);
        jPaneRegistarVentaProducto.setLayout(jPaneRegistarVentaProductoLayout);
        jPaneRegistarVentaProductoLayout.setHorizontalGroup(
            jPaneRegistarVentaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneRegistarVentaProductoLayout.createSequentialGroup()
                .addGroup(jPaneRegistarVentaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneRegistarVentaProductoLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblPuesto))
                    .addGroup(jPaneRegistarVentaProductoLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaneRegistarVentaProductoLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaneRegistarVentaProductoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblSelProducto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneRegistarVentaProductoLayout.createSequentialGroup()
                .addGap(0, 116, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPaneRegistarVentaProductoLayout.setVerticalGroup(
            jPaneRegistarVentaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneRegistarVentaProductoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPuesto)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblSelProducto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        getContentPane().add(jPaneRegistarVentaProducto);
        jPaneRegistarVentaProducto.setBounds(0, 0, 624, 440);

        setBounds(0, 0, 640, 485);
    }// </editor-fold>//GEN-END:initComponents

    private void lstPuestosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPuestosValueChanged
        panelProductos.removeAll();
        cargarBotones();
    }//GEN-LAST:event_lstPuestosValueChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void cargar() {
        lstPuestos.setListData(this.modelo.getListaPuestos().toArray());
    }

    public void cargarBotones() {
        Puesto puesto = (Puesto) lstPuestos.getSelectedValue();
        if (lstPuestos.getSelectedValue() != null) {
            ArrayList<Producto> productos = puesto.obtenerProductos();
            productos.sort(null);
            // Establecer el layout del panel como GridLayout
            panelProductos.setLayout(new GridLayout((int) Math.ceil((double) productos.size() / 2), 2)); // 3 columnas y un número variable de filas

            for (Producto producto : productos) {
                if (puesto.obtenerStockProducto(producto) > 0) { // Solo mostrar productos con stock disponible
                    JButton nuevo = new JButton();
                    String rutaImagen = "ImagenesOblig\\" + producto.getRutaImagen();
                    nuevo.setIcon(new ImageIcon(new ImageIcon(rutaImagen).getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT))); // Establecer el tamaño del ícono en 60x60
                    nuevo.setToolTipText(producto.getNombre()); // Mostrar el nombre del producto al pasar el mouse por encima
                    nuevo.addActionListener(new ProcesoProducto());
                    nuevo.setPreferredSize(new Dimension(180, 80));
                    panelProductos.add(nuevo);
                }
            }
            if (productos.size() == 1) {
                JButton emparejar = new JButton();
                emparejar.setPreferredSize(new Dimension(180, 80));
                emparejar.setVisible(false);
                panelProductos.add(emparejar);
            }
            this.revalidate();
            this.repaint();
        }
    }

    private class ProcesoProducto implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            // este código se ejecutará al presionar el botón, obtengo cuál botón
            JButton cual = ((JButton) e.getSource());
            JSpinner cantidadSpinner = new JSpinner();
            JSpinner costoSpinner = new JSpinner();
            JLabel stockActual = new JLabel();

            Object[] message = {
                "Cantidad a vender:", cantidadSpinner,
                "Costo de la venta:", costoSpinner,
                "Stock actual: ", stockActual
            };

            Puesto puesto = (Puesto) lstPuestos.getSelectedValue();
            Producto prod = modelo.obtenerProductoEnPuestoPorNombre(puesto, cual.getToolTipText());
            stockActual.setText(stockActual.getText() + puesto.obtenerStockProducto(prod) + " " + Utilidades.devolverTipoVentaAMostrar(prod.getFormaVenta(), puesto.obtenerStockProducto(prod)));
            int option = JOptionPane.showConfirmDialog(null, message, "Ingrese los datos", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                int cantidad = (int) (cantidadSpinner.getValue());
                int costo = (int) (costoSpinner.getValue());
                if (cantidad > 0 && costo > 0 && modelo.realizarVentaProducto(puesto, prod, costo, cantidad, TIPO_MOVIMIENTO)) {
                    JOptionPane.showMessageDialog(null, "Se ha realizado la venta con éxito..", "Informacion del sistema.", JOptionPane.INFORMATION_MESSAGE);
                } else if (cantidad > puesto.obtenerStockProducto(prod)) {
                    JOptionPane.showMessageDialog(null, "Error al realizar la venta, no tiene stock del producto.", "Informacion del sistema.", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Costo y cantidad deben ser mayor que cero.", "Informacion del sistema.", JOptionPane.ERROR_MESSAGE);
                }
            }
            panelProductos.removeAll();
            cargarBotones();
        }

    }

    public void propertyChange(PropertyChangeEvent evt) {
        cargar();
        panelProductos.removeAll();
        cargarBotones();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPaneRegistarVentaProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblSelProducto;
    private javax.swing.JList lstPuestos;
    private javax.swing.JPanel panelProductos;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;

} // Nicolas Rodriguez y Manuel Ackerman
